
services:
  
  devbox:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity

    depends_on:
      - apibox

    volumes:
      - "../..:/workspaces:cached"

    # Runs devbox on the same network as the database container (2d6server), allows "forwardPorts" in devcontainer.json function.
    network_mode: service:2d6server



  apibox:
    image: "mcr.microsoft.com/azure-databases/data-api-builder:latest"

    depends_on:
      - 2d6server

    volumes:
      - "../src/dab-config.json:/App/dab-config.json"

    # Runs devbox on the same network as the database container (2d6server), allows "forwardPorts" in devcontainer.json function.
    network_mode: service:2d6server



  2d6server:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: '2d6db'
      MYSQL_USER: 'frank'
      MYSQL_PASSWORD: myPassword
      MYSQL_ROOT_PASSWORD: rootPassword
    # ports:
    #   - "3306:3306"
    volumes:
      - "./scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./scripts/data.sql:/docker-entrypoint-initdb.d/2.sql"

